name: test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Give gradlew shell scripts permission to execute
      run: find . -name "**gradlew" -exec chmod u+x {} \;

    - name: Test
      run: make test
